### PR TITLE
MGMT-14762: Fix podman

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
@danielerez seems like the pullsecret file is not created as expected: https://gist.github.com/nmagnezi/79de5af05aaced6d9e4d0e6a90093af1

**Comment by danielerez** [comment]
> @danielerez seems like the pullsecret file is not created as expected: https://gist.github.com/nmagnezi/79de5af05aaced6d9e4d0e6a90093af1

Seems the last pushed removed my fix: https://github.com/openshift/appliance/compare/56fbb73b9640229a075e764c0eb294067c91d0cf..31527a149a90dd06d4cbede39bb075f6b6f4bc59
Re-pushed from my branch now.

**Comment by nmagnezi** [comment]
> > @danielerez seems like the pullsecret file is not created as expected: https://gist.github.com/nmagnezi/79de5af05aaced6d9e4d0e6a90093af1
> 
> Seems the last pushed removed my fix: https://github.com/openshift/appliance/compare/56fbb73b9640229a075e764c0eb294067c91d0cf..31527a149a90dd06d4cbede39bb075f6b6f4bc59 Re-pushed from my branch now.

Correct. looks okay now.

**Comment by nmagnezi** [comment]
Generated an image via `make build run` and installation started:
Screenshot 2023-05-30 at 15 27 42

**Pull request merged**
