### PR TITLE
Fix UEFI boot on baremetal machines

### PR DESCRIPTION
**Pull request by danielerez**
Due to an issue in GRUB that has been recently fixed only in fedora[*], boot fails on kernel panic in some machines.
The exact failure is an 'out of memory' that is thrown since we load the full rootfs.img to memory using initrd.
Hence, till the fix is backported to rhcos, we can manually override the EFI dir during the appliance disk image build.

Note: a limitation of the solution is that it won't work using secure boot mode. I.e. we'll have to require UEFI + Secure Boot disabled.

[*] https://github.com/rhboot/grub2/commit/a048b2280ae6a2cf90fd5d2960823843e17e4d66

### CODE REVIEW

**Comment by danielerez** [comment]
@oourfali 
@jhernand 
@nmagnezi

**Comment by jhernand** [comment]
@danielerez should the `efi.tar.gz` included in the patch? I don't see it.

Why will this affect secure boot? As long as the new EFI binaries are correctly signed they should work fine with secure boot.

**Comment by danielerez** [comment]
> @danielerez should the `efi.tar.gz` included in the patch? I don't see it.

yeah, added now:)

> 
> Why will this affect secure boot? As long as the new EFI binaries are correctly signed they should work fine with secure boot.

Seems that replacing the EFI binaries on an RHCOS image with the ones from Fedora CoreOS raises 'bad shim signature' error when secure boot is enabled: https://imgur.com/a/NFzjWzL

**Review by jhernand — APPROVED** [review]
Looks good to me, thanks @danielerez.

**Pull request merged**
