### PR TITLE
MGMT-15043: changed recovery grub menu item text

### PR DESCRIPTION
**Pull request by danielerez**
To emphasis the usage of recovery menu item, added the following text: '(Reinstall Cluster)'

### CODE REVIEW

**Review by nmagnezi — CHANGES_REQUESTED** [review]
Please update here as well: https://github.com/openshift/appliance/blob/master/docs/user-guide.md#recovery--reinstall

**Comment by danielerez** [comment]
> Please update here as well: https://github.com/openshift/appliance/blob/master/docs/user-guide.md#recovery--reinstall

done

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Pull request merged**
